version: 0.1.{build}

skip_commits:
  message: /update readme.*/

os: WMF 5

install:
  - ps: Install-PackageProvider -Name NuGet -Confirm:$false -Force -ErrorAction Stop | Out-Null
  - ps: Install-Module -Name Pester, PSScriptAnalyzer, PlatyPS -Confirm:$false -Force -ErrorAction SilentlyContinue | Out-Null

build: false

build_script:
  - ps: . ./build/build.ps1

deploy_script:
  - ps: . ./build/deploy.ps1

environment:
  PSGallery_Api_Key:
    secure: GLpDCkv0jnOaH78jkwaFRMMqnYe2SZ8jkZQ1iPpT6qEK9utBpkYRpDJAj1xeIKK/

